<a href="https://colab.research.google.com/github/syedaBasmaAfreen/python-DA-ML/blob/main/python_Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ⌨   Day 6

*DA with python*

* to use array in python we have to include library called numpy.
    ***import numpy as np***
*  arrays are  50x faster than list
bcz arrays store in contigious memory location


In [ ]:
import numpy as np
r1=np.array([1,2,3,4,5,6,7,8])#if we do not type cast (np.array)it will conidr it as list

r2=np.array(['a','b','c','d','e'])

r3=np.array([2.0,1.3,2.4,5.6,7.6])

r4=np.array(["syeda","basma","afreen","mca","internship"])
  #print(r1.append(10))
print(r1[0])
print(r2[0])                                                   #accessing
print(r3[0])
print(r4[0])

r1[0]=99999
print(r1)                                                 #modifying



print(r2[1:4])
print(r1[: : 2])                                    # subset
print(r1[: : -2])

print(len(r1))

print(r1.dtype)                          #type of array
print(r3.dtype)



print(r1[1]+r1[2])            # concatenate
print(r4[0]+r4[1]+r4[2])




#print(r1[0]=000000)expression cannot contain assignment, perhaps you meant "=="?






In [ ]:
#sorting array

import numpy as np

sr=np.array(['l','a','b','c','d','e'])

#r5.append('k')
#print(r5)
sr.sort()
print(sr)

In [ ]:
#spliting array


spi=np.array([1,2,3,4,5,6,7,8,9,10,11,12])#split array in 3parts
new_arr=np.array_split(spi,3)
print(new_arr)
print(new_arr[0])

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[1 2 3 4]


In [ ]:
r11=np.array([1,2,3,4,5,6,7,8])#1d ;containing the values
r22=np.array([[1,2,3,4],[5,6,7,8]])#2D; 1-D arrays as its element
r33=np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[5,6,7,8]]])#3D ;2d array as ele


array=np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])

print(r11)


print(r22)

print(r33)



print(array.ndim)
print(array)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3 4]
  [5 6 7 8]]

 [[5 6 7 8]
  [5 6 7 8]]]
3
[[[1 2 3 4]
  [5 6 7 8]
  [5 6 7 8]]]


In [ ]:
r11=np.array([1,2,3,4,5,6,7,8])
r22=np.array([[[[[[1,2,3,4],[5,6,7,8],[1,2,3,4]]]]]])
r33=np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
r44=np.array([[[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[5,6,7,8]]]])
print(r11.ndim)                                                #  no of brackets
print(r22.ndim)
print(r33.ndim)
print(r44.ndim)


1
6
3
4


In [ ]:
arr11 = np.array(42)
arr22 = np.array([1, 2, 3, 4, 5],ndmin=5)                   #creating dimensions
arr33= np.array([[1, 2, 3], [4, 5, 6]],ndmin=7)



print(arr11)


print(arr22)


print(arr33)




42
[[[[[1 2 3 4 5]]]]]
[[[[[[[1 2 3]
      [4 5 6]]]]]]]


In [ ]:
arr33= np.array([[1, 2, 3], [4, 5, 6]],ndmin=8)
print(arr33)
print(arr33.ndim)

[[[[[[[[1 2 3]
       [4 5 6]]]]]]]]
8


**Shape of array**

In [ ]:
r=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
print(r.shape)

(12,)


In [ ]:
r=np.array([[1,2,3,4,5,6,7,8,9,10,11,12,]])
print(r.shape)

(1, 12)


In [ ]:
r=np.array([[1,2,3,4,5,6,],[7,8,9,10,11,12,]])
print(r)
print(r.shape)#2 is no of6  brackets  &  6 is ele prsnt in each bracket

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
r=np.array([[[1,2,3,4,5,6,]],[[7,8,9,10,11,12,]]])
print(r)
print(r.shape)

[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]
(2, 1, 6)


In [ ]:
import numpy as np
r=np.array([[[1,2,3,4,5,6,],[7,8,9,10,11,12,]]])
print(r)
print(r.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]
(1, 2, 6)


In [ ]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)
print(ar.shape)
print(ar.ndim)
new=ar.reshape(3,2,2)
print(new)
print(new.shape)
print(new.ndim)

# convert 1d into 2d


In [ ]:
r11=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
r222=r11.reshape(2,6)
print(r222)
r111=r11.reshape(4,3)
print(r111)

# converting 1D into 3D

In [ ]:
r10=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
r20=r10.reshape(3,2,2)
print(r20)
print(r20.shape)
print(r10.ndim)
print(r20.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
1
3


In [ ]:
rr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])#doubt
#new1=rr1.reshape(3,2,2)     #rows dim column

new2=rr1.reshape(2,3,2)
print(rr1.ndim)
print(new2.ndim)

1
3


# Converting Multi D into 1d

In [ ]:
array1=np.array([[1,2,3],[4,5,6]])
print(array1)
new=array1.reshape(-1)
print(new)


In [ ]:
array1=np.array([[1,2,3],[4,5,6],[2,2,3]])
print(array1)
new=array1.reshape(-1)
print(new)


2d array

In [ ]:
ay=np.array([[1,2,3],[4,5,6]])
print(ay)
print(ay[0])
print(ay[1])


print(ay[0][1:5])
print(ay[0,1])#Access the element on the first row, second column
print(ay.shape)
print(ay.ndim)
print(ay.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
[2 3]
2
(2, 3)
2
[[1 2]
 [3 4]
 [5 6]]


In [ ]:

ay1=np.array([[[[1,2,3,4],[5,6,7,8],[5,6,7,8],[5,6,7,8]]]])
print(ay1)
print(ay1.ndim)
print(ay1.reshape(2,8))
print(ay1.ndim)
print(ay1.reshape(4,4))
print(ay1.ndim)
print(ay1.reshape(8,2))

[[[[1 2 3 4]
   [5 6 7 8]
   [5 6 7 8]
   [5 6 7 8]]]]
4
[[1 2 3 4 5 6 7 8]
 [5 6 7 8 5 6 7 8]]
4
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
4
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [5 6]
 [7 8]
 [5 6]
 [7 8]]


**Iterating means going through elements one by one**
1. If we iterate on a 1-D array it will go through each element one by one.



In [ ]:
loop=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for x in loop:
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


2. In a 2-D array it will go through all the rows

In [ ]:
loop2=np.array([[1,2,3],[4,5,6]])
for y in loop2:

    print(y)


[1 2 3]
[4 5 6]


3. we have to iterate the arrays in each dimension

In [ ]:
loop3=np.array([[1,2,3],[4,5,6]])
for x in loop3:
  for y in x:
    print(y)


1
2
3
4
5
6


In [ ]:
loop4= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in loop4:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# filtering array
1. the new array contains only the values where the filter array had the value True, in this case, index 0 and 2

In [ ]:
ARRAY=np.array([10,20,30,40,50])
f=[True,False,True,False,True]#creating a new array
newarr=ARRAY[f]
print(newarr)

[10 30 50]


In [ ]:
ARRAY=np.array([10,20,30,40,50])
arr=[]
for x in ARRAY :
  if x>20:
   print("yes")
  else:
    print('no')

no
no
yes
yes
yes


In [ ]:
ARRAY=np.array([10,20,30,40,50])
filter_arr=[]
for x in ARRAY :
  if x>20:
   filter_arr.append(True)
  else:
   filter_arr.append(False)
print(filter_arr)
new=ARRAY[filter_arr]
print(new)

[False, False, True, True, True]
[30 40 50]


In [ ]:

import numpy as np

array=np.array([1,2,3,4,5,6,7,8,9,10])
findall_even=[]
findall_odd=[]

for y in array :
  if y %2 == 0 :
    findall_even.append(True)
  else:
   findall_even.append(False)
print(findall_even)
new=array[findall_even]
print(new)
new2=array[findall_odd]
print(new2)


[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]
[]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

# Create an empty list
even =[]
odd=[]

# go through each element in arr
for element in arr:
for y in arr:

  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    even.append(True)
  elif y %  2!=0:
    odd.append(True)
  else:
    even.append(False)